.TH "FOLDERSYNC" "1" "October 2018" "foldersync 1.0.0" ""
.SH NAME
FolderSync \- Folder synchronization software
.SH SYNOPSIS
.B foldersync
.SH DESCRIPTION
FolderSync is a utility to keep your backups up to date. You can 
visualise the differences between your data and your backup and choose 
what will be copied and what will be suppressed. The frequent 
synchronisation paths can be saved as favorites.
.SH AUTHOR
FolderSync is developped by Juliette Monsel <j_4321@protonmail.com>
.SH BUGS
Please submit bugs on the Github page of the project
\fBhttps://github.com/j4321/FolderSync/issues\fR 
or send an email to <j_4321@protonmail.com>.
