#! /usr/bin/python3
# -*- coding:Utf-8 -*-
"""
FolderSync - Folder synchronization software
Copyright 2017 Juliette Monsel <j_4321@protonmail.com>

FolderSync is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

FolderSync is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

Main
"""


import os
from foldersynclib.constantes import save_config, LOG_COPIE, LOG_SUPP
from foldersynclib.sync import Sync

try:
    sync = Sync()
    sync.mainloop()
finally:
    save_config()
    # delete logs
    if os.path.exists(LOG_COPIE):
        os.remove(LOG_COPIE)
    if os.path.exists(LOG_SUPP):
        os.remove(LOG_SUPP)
    try:
        sync.unlink()
    except Exception:
        pass
